graph TD
    IntroFeature: --> IntroFeature:.State
    IntroFeature: --> IntroFeature:.Action
    IntegrationFeature: --> IntegrationFeature:.State
    IntegrationFeature: --> IntegrationFeature:.Action
    BoardingFeature: --> BoardingFeature:.State
    BoardingFeature: --> BoardingFeature:.Action
    KimaiFeature: --> KimaiFeature:.State
    KimaiFeature: --> KimaiFeature:.Action
    LoginFeature: --> LoginFeature:.State
    LoginFeature: --> LoginFeature:.Action
    DebugFeature: --> DebugFeature:.State
    DebugFeature: --> DebugFeature:.Action
